drupal:
  settings:
    db_url: "mysql://user:pass@localhost/db"
    databases:
      default:
        default:
          database: dbNAME
          username: dbUSER
          password: dbPASS
          driver: mysql
